### ISSUE TITLE
ERROR `/JdvpCodeTabs-baseurl/assets/codeblock.css' not found

### ISSUE THREAD

**Issue by Clement-Jean** [jdvp/jdvp-codetabs-commonmark#4]
I'm trying to use your gem for my jekyll blog and it apparently can't find the css file. I added it into my asset folder but no success. Is there a way to set the `JdvpCodeTabs-baseurl` to another path ?

**Comment by jdvp** [comment]
codeblock.css should be copied in from the gem at build time. Does it exist anywhere in you `_site` directory after building? Or is this an error during build time?

Further, `JdvpCodeTabs-baseurl` should be replaced with the actual `baseurl` provided in your `_config.yml`. Are you setting that variable?

**Comment by Clement-Jean** [comment]
It copies the css inside my asset directory not the _site one. I think this is because I'm setting the baseurl to an empty string. But then my page still ask for `/JdvpCodeTabs-baseurl/assets/codeblock.css`

**Comment by jdvp** [comment]
Does it happen to work if you set baseurl to `"/"` instead of `""`? Although idk if that's even valid.

I don't really have any ideas off the top of my head since I'm not much of a ruby expert but also because the replacement code is really really short:
```
Jekyll::Hooks.register :posts, :post_convert do |post|
  if post.content.include? "JdvpCodeTabs-baseurl"
    post.content = post.content.gsub("JdvpCodeTabs-baseurl", "#{post.site.baseurl}")
  end
end
```

maybe the hooks are not running properly for some reason? IDK if (or how) that can happen as long as you set it as the markdown converter
```
markdown: JdvpCodeTabsCommonMark
```

Just to double check, you're using the latest version? 0.1.3?

**Comment by jdvp** [comment]
Oh wait also 
> inside my asset directory not the _site

It's not in _site/assets ???? I didn't even know jekyll would allow generated files to be placed not inside the _site dir

**Comment by Clement-Jean** [comment]
Sorry, my bad, it is in _site/assets. I think the problem come with my setup. I have 2 branches, one (working) for writing and the master one for the generated code. Once I build the site, I copy everything from _site into the master branch. This might create some problem. If you want to check, you might get more idea: https://github.com/Clement-Jean/clement-jean.github.io

**Comment by jdvp** [comment]
Oh I see. Yeah looking around the structure wasn't really what I was expecting but also I was wondering can you link me to a page that isn't working? 

JW bc like the first one I checked
https://clement-jean.github.io/grpc_go_embeddings/
seems to be working?

**Comment by jdvp** [comment]
Oh I see the issue on the main page, looking into it a bit more

https://clement-jean.github.io/

**Comment by jdvp** [comment]
<img width="489" alt="Screenshot 2023-01-04 at 11 45 59 PM" src="https://user-images.githubusercontent.com/7111196/210728021-a17f8986-44f0-496b-b288-5b1d17aa3e40.png">

So each post item on your index is adding links to the codeblocks files even though index doesn't really need to have reference to them.
That being said you should be able to resolve the issue by replacing `post.excerpt` with something like `post.excerpt | strip_html` in your index.html although that will probably remove the links in the exercepts

**Comment by jdvp** [comment]
On my end, I will see if there is some way to not be picked up by `post.except` (maybe the links aren't in the header item for each post, idk how I would go about accomplishing that) and also see if there is a Jekyll Hook for all pages (not just posts) to replace the URL in all pages rather than just posts as the plugin is currently doing

**Comment by Clement-Jean** [comment]
> post.excerpt | strip_html

This sounds like a good temporary fix.



> On my end, I will see if there is some way to not be picked up by `post.except` (maybe the links aren't in the header item for each post, idk how I would go about accomplishing that) and also see if there is a Jekyll Hook for all pages (not just posts) to replace the URL in all pages rather than just posts as the plugin is currently doing

Thank you for this, let me know if I can help somehow

**Comment by jdvp** [comment]
Sure, thanks for exposing the issue! I can't promise timeliness here bc it's a hobby you know but I'll try to work on it by the weekend if I can (hopefully it's something easy to fix!!!). Will leave this issue open til resolution

**Comment by jdvp** [comment]
@Clement-Jean This should all be resolved in v1.0.0

Release notes on what I changed here: https://github.com/jdvp/jdvp-codetabs-commonmark/releases/tag/v1.0.0

You should be able to use regular `post.excerpt` now I believe. Thanks again for highlighting the issues and lmk if any more issues arise

**Comment by Clement-Jean** [comment]
This removed the main page problem. Unfortunately, I think it is still a problem, I get this now:
```
ERROR `/packed_vs_unpacked_repeated_fields/JdvpCodeTabs-baseurl/assets/codeblock.css' not found.
```
and it breaks the code snippets: ![image](https://user-images.githubusercontent.com/16657553/211180435-fca81381-5279-4bd6-8f12-b707fc925d11.png)

**Comment by jdvp** [comment]
@Clement-Jean are you sure it's using the latest version? JW since `JdvpCodeTabs-baseurl` no longer even appears in the gem

**Comment by Clement-Jean** [comment]
In my Gemfile:

```
gem "jdvp-codetabs-commonmark", "~> 1.0.0"
```

I installed and cleaned the old versions. I'm also not a ruby expert so I'm not sure...

**Comment by jdvp** [comment]
lol also not a ruby expert. Whenever I do it locally on my end when creating updates for the gem, I have a script that does this
```
bundle update
gem uninstall -aIx --user-install jdvp-codetabs-commonmark
```

then I clean the site which for me means deleting these
```
.jekyll-cache/
_site
Gemfile.lock
```
then re-running
```
bundle update
```

IDK if that does anything though lol

**Comment by Clement-Jean** [comment]
My bad, it was in the cache somewhere, I delete everything and reinstalled. However, the code snippets are still broken (like in the image shown).

**Comment by jdvp** [comment]
@Clement-Jean checked out your project to debug. I think the issue is because my lack of Ruby knowledge. I was trying to find all html files using `Dir.glob(*.html)` but should have been using `Dir.glob(**/*.html)` so it would recurse the other directories in `_site` as well. 

Give me a min to make the change and push a new version lol

**Comment by jdvp** [comment]
@Clement-Jean Should be fixed in v1.0.1 (fingers crossed at least hahaha)

**Comment by Clement-Jean** [comment]
Looks like its working, nice job!

**Comment by jdvp** [comment]
Glad I don't have to look into another issue straight away! Hope it keeps working well for you but feel free to open another ticket if anything goes wrong

**Comment by Clement-Jean** [comment]
> Glad I don't have to look into another issue straight away! Hope it keeps working well for you but feel free to open another ticket if anything goes wrong 

Do you accept feature requests in issues ? it's not urgent, just small ideas

**Comment by jdvp** [comment]
I think it depends on the feature, but I wouldn't mind reviewing issues and seeing if I think it's feasible / a direction I want to go with the project!
